# Trigger on pull request to master (+ allow manual runs of this workflow)
# Checkout repo, install Node.js, run test


name: pr-workflow

on:
  push:
    branches: [master]
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install & Tests
        run: |
          npm install
          npm test
